CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "name" varchar,
  "oauth_google_id" varchar,
  "oauth_line_id" varchar,
  "is_guest" boolean,
  "status" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "user_addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "recipient_name" varchar,
  "recipient_phone" varchar,
  "address_line" varchar,
  "is_default" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "parent_id" int,
  "is_active" boolean,
  "sort_order" int,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "category_id" int,
  "description" text,
  "material" varchar,
  "price" int,
  "stock_quantity" int,
  "is_active" boolean,
  "is_featured" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "image_url" varchar,
  "alt_text" varchar,
  "sort_order" int,
  "created_at" datetime
);

CREATE TABLE "favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "created_at" datetime
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "session_id" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int,
  "product_id" int,
  "quantity" int,
  "unit_price" int,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_number" varchar UNIQUE,
  "user_id" int,
  "status" varchar,
  "payment_status" varchar,
  "payment_method" varchar,
  "total_amount" int,
  "shipping_fee" int,
  "recipient_name" varchar,
  "recipient_phone" varchar,
  "shipping_address" text,
  "shipping_type" varchar,
  "notes" text,
  "placed_at" datetime,
  "paid_at" datetime,
  "shipped_at" datetime,
  "completed_at" datetime,
  "cancelled_at" datetime,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "product_name" varchar,
  "unit_price" int,
  "quantity" int,
  "subtotal_amount" int,
  "created_at" datetime
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "gateway" varchar,
  "transaction_id" varchar,
  "amount" int,
  "currency" varchar,
  "status" varchar,
  "paid_at" datetime,
  "raw_response" text,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "admin_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "password_hash" varchar,
  "name" varchar,
  "role" varchar,
  "status" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

COMMENT ON TABLE "user_addresses" IS '用於會員常用收件地址管理';

COMMENT ON TABLE "products" IS '若未來有多規格，可以再拆出 product_variants';

COMMENT ON TABLE "favorites" IS '同一 user + product 可加 unique 限制';

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
